name: Release and Update Formula

permissions:
    contents: write

on:
    push:
        branches:
            - main

jobs:
    release-and-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Extract version from Cargo.toml
              run: |
                version=$(grep '^version =' Cargo.toml | awk -F= '{gsub(/^[[:space:]]+/, "", $2); print $2}' | tr -d \") 
                echo "VERSION=$version" >> $GITHUB_ENV
                echo "Tagging version: v$VERSION"
            - name: Create Git tag if it doesn't exist
              run: |
                if git ls-remote --tags origin "refs/tags/v$VERSION" | grep -q "refs/tags/v$VERSION"; then
                    echo "Tag v$VERSION already exists. Skipping."
                else
                    git config user.name "GitHub Actions"
                    git config user.email "actions@github.com"
                    git tag "v$VERSION"
                    git push origin "v$VERSION"
                fi
            - name: Create GitHub release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                if gh release view "v$VERSION" --repo "$GITHUB_REPOSITORY" >/dev/null 2>&1; then
                    echo "Release v$VERSION already exists. Skipping."
                else
                    gh release create "v$VERSION" --repo "$GITHUB_REPOSITORY" --title "Release v$VERSION" --generate-notes
                fi
            - name: Trigger Homebrew formula update
              run: |
                gh api \
                  --method POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  -H "Authorization: token ${{ secrets.HOMEBREW_TOKEN }}" \
                  '/repos/charliekarafotias/homebrew-tools/actions/workflows/update-astra-formula.yml/dispatches' \
                  -f 'ref=main' \
                  -f 'inputs[version]=$VERSION'  
