name: Release and Update Formula

permissions:
    contents: write

on:
    push:
        branches:
            - main

jobs:
    release-and-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Extract version from Cargo.toml
              run: |
                version=$(grep '^version =' Cargo.toml | head -n1 | awk -F= '{print $2}' | tr -d \")
                echo "VERSION=$version" >> $GITHUB_ENV
                echo "Tagging version: v$VERSION"
            - name: Create Git tag
              run: |
                git config user.name "GitHub Actions"
                git config user.email "actions@github.com"
                git tag "v$VERSION"
                git push origin "v$VERSION"
            - name: Create GitHub release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gh release create "v$VERSION" --repo "$GITHUB_REPOSITORY" --title "Release v$VERSION" --generate-notes
            - name: Trigger Homebrew formula update
              run: |
                gh api \
                  --method POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  - H "Authorization: token ${{ secrets.HOMEBREW_TOKEN }}" \
                  '/repos/charliekarafotias/homebrew-tools/actions/workflows/update-astra-formula.yml/dispatches' \
                  -f 'ref=main' \
                  -f 'inputs[version]=$VERSION'  
